### ISSUE TITLE
`summary_avg_time': undefined method `sum' for #<Array:0x000000020f8280> (NoMethodError)

### ISSUE THREAD

**Issue by srikanthjeeva** [gastzars/gas_load_tester#1]
Getting this error when running the example

```
require 'gas_load_tester'

simple_test = GasLoadTester::Test.new({client: 100, time: 5})
simple_test.run(output: true, file_name: '/load_test/results/ui_100') do
  RestClient.get("http://someurl.com", {})
end
```

```
/homes/.rvm/gems/ruby-2.3.1/gems/gas_load_tester-1.0.13/lib/gas_load_tester/test.rb:74:in `summary_avg_time': undefined method `sum' for #<Array:0x000000020f8280> (NoMethodError)
	from /homes/.rvm/gems/ruby-2.3.1/gems/gas_load_tester-1.0.13/lib/gas_load_tester/chart_builder.rb:169:in `build_summary'
	from /homes/.rvm/gems/ruby-2.3.1/gems/gas_load_tester-1.0.13/lib/gas_load_tester/chart_builder.rb:160:in `build_sum_test'
	from /homes/.rvm/gems/ruby-2.3.1/gems/gas_load_tester-1.0.13/lib/gas_load_tester/chart_builder.rb:47:in `build_body'
	from /homes/.rvm/gems/ruby-2.3.1/gems/gas_load_tester-1.0.13/lib/gas_load_tester/test.rb:61:in `export_file'
	from /homes/.rvm/gems/ruby-2.3.1/gems/gas_load_tester-1.0.13/lib/gas_load_tester/test.rb:43:in `run'
	from load_test.rb:4:in `<main>'

```

**Comment by ktzoulas** [comment]
Raised [pull request](https://github.com/gastzars/gas_load_tester/pull/2) to fix this issue.
